import React from 'react'
import type { Metadata } from 'next'
import StyledComponentsRegistry from './AntdRegistry'
import './globals.scss'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
}

function RootLayout({ children }: RootLayoutProps) {
  return (

    <html lang="en">
      <body>
        <StyledComponentsRegistry>
            {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}

export default RootLayout
